version: '3'

services:
  ssm-server:
    build: ./.environment
    image: ssm
    depends_on:
      - mysql
      - mysql-test
      - redis
    volumes:
      - ./:/ssm:cached

  queue-server:
    build: ./.environment
    image: ssm
    command: php artisan queue:work
    depends_on:
      - mysql
    volumes:
      - ./:/ssm:cached

  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  mysql-test:
    image: mysql
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=${DB_DATABASE_TEST}
      - MYSQL_USER=${DB_USERNAME_TEST}
      - MYSQL_PASSWORD=${DB_PASSWORD_TEST}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD_TEST}
    volumes:
      - ./storage/tmp/test:/var/lib/mysql:cached
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./.environment/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./public:/ssm/public:cached
    depends_on:
      - ssm-server

  redis:
    image: redis
    ports:
      - '6379:6379'

  echo-server:
    image: node
    ports:
      - 8888:8888
    working_dir: /ssm
    volumes:
      - .:/ssm:cached
    depends_on:
      - redis
      - ssm-server
    command: 'npm start'
