<?php

use App\Models\Token;
use App\Models\LocationCountry;
use Illuminate\Database\Seeder;

class LocationCountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            [
                'name' => 'Albania',
                'iso_alpha_2' => 'AL',
                'iso_alpha_3' => 'ALB',
                'iso_numeric' => '8',
                'international_phone' => '355',
            ],
            [
                'name' => 'Andorra',
                'iso_alpha_2' => 'AD',
                'iso_alpha_3' => 'AND',
                'iso_numeric' => '20',
                'international_phone' => '376',
            ],
            [
                'name' => 'Austria',
                'iso_alpha_2' => 'AT',
                'iso_alpha_3' => 'AUT',
                'iso_numeric' => '40',
                'international_phone' => '43',
            ],
            [
                'name' => 'Belarus',
                'iso_alpha_2' => 'BY',
                'iso_alpha_3' => 'BLR',
                'iso_numeric' => '112',
                'international_phone' => '375',
            ],
            [
                'name' => 'Belgium',
                'iso_alpha_2' => 'BE',
                'iso_alpha_3' => 'BEL',
                'iso_numeric' => '56',
                'international_phone' => '32',
            ],
            [
                'name' => 'Bosnia and Herzegovina',
                'iso_alpha_2' => 'BA',
                'iso_alpha_3' => 'BIH',
                'iso_numeric' => '70',
                'international_phone' => '387',
            ],
            [
                'name' => 'Bulgaria',
                'iso_alpha_2' => 'BG',
                'iso_alpha_3' => 'BGR',
                'iso_numeric' => '100',
                'international_phone' => '359',
            ],
            [
                'name' => 'Croatia',
                'iso_alpha_2' => 'HR',
                'iso_alpha_3' => 'HRV',
                'iso_numeric' => '191',
                'international_phone' => '385',
            ],
            [
                'name' => 'Cyprus',
                'iso_alpha_2' => 'CY',
                'iso_alpha_3' => 'CYP',
                'iso_numeric' => '196',
                'international_phone' => '357',
            ],
            [
                'name' => 'Czech Republic',
                'iso_alpha_2' => 'CZ',
                'iso_alpha_3' => 'CZE',
                'iso_numeric' => '203',
                'international_phone' => '420',
            ],
            [
                'name' => 'Denmark',
                'iso_alpha_2' => 'DK',
                'iso_alpha_3' => 'DNK',
                'iso_numeric' => '208',
                'international_phone' => '45',
            ],
            [
                'name' => 'East Germany',
                'iso_alpha_2' => 'DD',
                'iso_alpha_3' => 'DDR',
                'iso_numeric' => '278',
                'international_phone' => '37',
            ],
            [
                'name' => 'Estonia',
                'iso_alpha_2' => 'EE',
                'iso_alpha_3' => 'EST',
                'iso_numeric' => '233',
                'international_phone' => '372',
            ],
            [
                'name' => 'Faroe Islands',
                'iso_alpha_2' => 'FO',
                'iso_alpha_3' => 'FRO',
                'iso_numeric' => '234',
                'international_phone' => '298',
            ],
            [
                'name' => 'Finland',
                'iso_alpha_2' => 'FI',
                'iso_alpha_3' => 'FIN',
                'iso_numeric' => '246',
                'international_phone' => '358',
            ],
            [
                'name' => 'France',
                'iso_alpha_2' => 'FR',
                'iso_alpha_3' => 'FRA',
                'iso_numeric' => '250',
                'international_phone' => '33',
            ],
            [
                'name' => 'Germany',
                'iso_alpha_2' => 'DE',
                'iso_alpha_3' => 'DEU',
                'iso_numeric' => '276',
                'international_phone' => '49',
            ],
            [
                'name' => 'Gibraltar',
                'iso_alpha_2' => 'GI',
                'iso_alpha_3' => 'GIB',
                'iso_numeric' => '292',
                'international_phone' => '350',
            ],
            [
                'name' => 'Greece',
                'iso_alpha_2' => 'GR',
                'iso_alpha_3' => 'GRC',
                'iso_numeric' => '300',
                'international_phone' => '30',
            ],
            [
                'name' => 'Guernsey',
                'iso_alpha_2' => 'GG',
                'iso_alpha_3' => 'GGY',
                'iso_numeric' => '831',
                'international_phone' => '44',
            ],
            [
                'name' => 'Hungary',
                'iso_alpha_2' => 'HU',
                'iso_alpha_3' => 'HUN',
                'iso_numeric' => '348',
                'international_phone' => '36',
            ],
            [
                'name' => 'Iceland',
                'iso_alpha_2' => 'IS',
                'iso_alpha_3' => 'ISL',
                'iso_numeric' => '352',
                'international_phone' => '354',
            ],
            [
                'name' => 'Ireland',
                'iso_alpha_2' => 'IE',
                'iso_alpha_3' => 'IRL',
                'iso_numeric' => '372',
                'international_phone' => '353',
            ],
            [
                'name' => 'Isle of Man',
                'iso_alpha_2' => 'IM',
                'iso_alpha_3' => 'IMN',
                'iso_numeric' => '833',
                'international_phone' => '44',
            ],
            [
                'name' => 'Italy',
                'iso_alpha_2' => 'IT',
                'iso_alpha_3' => 'ITA',
                'iso_numeric' => '380',
                'international_phone' => '39',
            ],
            [
                'name' => 'Jersey',
                'iso_alpha_2' => 'JE',
                'iso_alpha_3' => 'JEY',
                'iso_numeric' => '832',
                'international_phone' => '44',
            ],
            [
                'name' => 'Latvia',
                'iso_alpha_2' => 'LV',
                'iso_alpha_3' => 'LVA',
                'iso_numeric' => '428',
                'international_phone' => '371',
            ],
            [
                'name' => 'Liechtenstein',
                'iso_alpha_2' => 'LI',
                'iso_alpha_3' => 'LIE',
                'iso_numeric' => '438',
                'international_phone' => '423',
            ],
            [
                'name' => 'Lithuania',
                'iso_alpha_2' => 'LT',
                'iso_alpha_3' => 'LTU',
                'iso_numeric' => '440',
                'international_phone' => '370',
            ],
            [
                'name' => 'Luxembourg',
                'iso_alpha_2' => 'LU',
                'iso_alpha_3' => 'LUX',
                'iso_numeric' => '442',
                'international_phone' => '352',
            ],
            [
                'name' => 'Macedonia',
                'iso_alpha_2' => 'MK',
                'iso_alpha_3' => 'MKD',
                'iso_numeric' => '807',
                'international_phone' => '389',
            ],
            [
                'name' => 'Malta',
                'iso_alpha_2' => 'MT',
                'iso_alpha_3' => 'MLT',
                'iso_numeric' => '470',
                'international_phone' => '356',
            ],
            [
                'name' => 'Metropolitan France',
                'iso_alpha_2' => 'FX',
                'iso_alpha_3' => 'FXX',
                'iso_numeric' => '249',
                'international_phone' => null,
            ],
            [
                'name' => 'Moldova',
                'iso_alpha_2' => 'MD',
                'iso_alpha_3' => 'MDA',
                'iso_numeric' => '498',
                'international_phone' => '373',
            ],
            [
                'name' => 'Monaco',
                'iso_alpha_2' => 'MC',
                'iso_alpha_3' => 'MCO',
                'iso_numeric' => '492',
                'international_phone' => '377',
            ],
            [
                'name' => 'Montenegro',
                'iso_alpha_2' => 'ME',
                'iso_alpha_3' => 'MNE',
                'iso_numeric' => '499',
                'international_phone' => '382',
            ],
            [
                'name' => 'Netherlands',
                'iso_alpha_2' => 'NL',
                'iso_alpha_3' => 'NLD',
                'iso_numeric' => '528',
                'international_phone' => '31',
            ],
            [
                'name' => 'Norway',
                'iso_alpha_2' => 'NO',
                'iso_alpha_3' => 'NOR',
                'iso_numeric' => '578',
                'international_phone' => '47',
            ],
            [
                'name' => 'Poland',
                'iso_alpha_2' => 'PL',
                'iso_alpha_3' => 'POL',
                'iso_numeric' => '616',
                'international_phone' => '48',
            ],
            [
                'name' => 'Portugal',
                'iso_alpha_2' => 'PT',
                'iso_alpha_3' => 'PRT',
                'iso_numeric' => '620',
                'international_phone' => '351',
            ],
            [
                'name' => 'Romania',
                'iso_alpha_2' => 'RO',
                'iso_alpha_3' => 'ROU',
                'iso_numeric' => '642',
                'international_phone' => '40',
            ],
            [
                'name' => 'Russia',
                'iso_alpha_2' => 'RU',
                'iso_alpha_3' => 'RUS',
                'iso_numeric' => '643',
                'international_phone' => '7',
            ],
            [
                'name' => 'San Marino',
                'iso_alpha_2' => 'SM',
                'iso_alpha_3' => 'SMR',
                'iso_numeric' => '674',
                'international_phone' => '378',
            ],
            [
                'name' => 'Serbia',
                'iso_alpha_2' => 'RS',
                'iso_alpha_3' => 'SRB',
                'iso_numeric' => '688',
                'international_phone' => '381',
            ],
            [
                'name' => 'Serbia and Montenegro',
                'iso_alpha_2' => 'CS',
                'iso_alpha_3' => 'SCG',
                'iso_numeric' => '891',
                'international_phone' => '381',
            ],
            [
                'name' => 'Slovakia',
                'iso_alpha_2' => 'SK',
                'iso_alpha_3' => 'SVK',
                'iso_numeric' => '703',
                'international_phone' => '421',
            ],
            [
                'name' => 'Slovenia',
                'iso_alpha_2' => 'SI',
                'iso_alpha_3' => 'SVN',
                'iso_numeric' => '705',
                'international_phone' => '386',
            ],
            [
                'name' => 'Svalbard and Jan Mayen',
                'iso_alpha_2' => 'SJ',
                'iso_alpha_3' => 'SJM',
                'iso_numeric' => '744',
                'international_phone' => '47',
            ],
            [
                'name' => 'Sweden',
                'iso_alpha_2' => 'SE',
                'iso_alpha_3' => 'SWE',
                'iso_numeric' => '752',
                'international_phone' => '46',
            ],
            [
                'name' => 'Switzerland',
                'iso_alpha_2' => 'CH',
                'iso_alpha_3' => 'CHE',
                'iso_numeric' => '756',
                'international_phone' => '41',
            ],
            [
                'name' => 'Ukraine',
                'iso_alpha_2' => 'UA',
                'iso_alpha_3' => 'UKR',
                'iso_numeric' => '804',
                'international_phone' => '380',
            ],
            [
                'name' => 'Union of Soviet Socialist Republics',
                'iso_alpha_2' => 'SU',
                'iso_alpha_3' => 'SUN',
                'iso_numeric' => '810',
                'international_phone' => '7',
            ],
            [
                'name' => 'United Kingdom',
                'iso_alpha_2' => 'GB',
                'iso_alpha_3' => 'GBR',
                'iso_numeric' => '826',
                'international_phone' => '44',
            ],
            [
                'name' => 'Vatican City',
                'iso_alpha_2' => 'VA',
                'iso_alpha_3' => 'VAT',
                'iso_numeric' => '336',
                'international_phone' => null,
            ],
            [
                'name' => 'Åland Islands',
                'iso_alpha_2' => 'AX',
                'iso_alpha_3' => 'ALA',
                'iso_numeric' => '248',
                'international_phone' => '358',
            ],
            [
                'name' => 'Algeria',
                'iso_alpha_2' => 'DZ',
                'iso_alpha_3' => 'DZA',
                'iso_numeric' => '12',
                'international_phone' => '213',
            ],
            [
                'name' => 'Benin',
                'iso_alpha_2' => 'BJ',
                'iso_alpha_3' => 'BEN',
                'iso_numeric' => '204',
                'international_phone' => '229',
            ],
            [
                'name' => 'Angola',
                'iso_alpha_2' => 'AO',
                'iso_alpha_3' => 'AGO',
                'iso_numeric' => '24',
                'international_phone' => '244',
            ],
            [
                'name' => 'Botswana',
                'iso_alpha_2' => 'BW',
                'iso_alpha_3' => 'BWA',
                'iso_numeric' => '72',
                'international_phone' => '267',
            ],
            [
                'name' => 'Burkina Faso',
                'iso_alpha_2' => 'BF',
                'iso_alpha_3' => 'BFA',
                'iso_numeric' => '854',
                'international_phone' => '226',
            ],
            [
                'name' => 'Burundi',
                'iso_alpha_2' => 'BI',
                'iso_alpha_3' => 'BDI',
                'iso_numeric' => '108',
                'international_phone' => '257',
            ],
            [
                'name' => 'Cameroon',
                'iso_alpha_2' => 'CM',
                'iso_alpha_3' => 'CMR',
                'iso_numeric' => '120',
                'international_phone' => '237',
            ],
            [
                'name' => 'Cape Verde',
                'iso_alpha_2' => 'CV',
                'iso_alpha_3' => 'CPV',
                'iso_numeric' => '132',
                'international_phone' => '238',
            ],
            [
                'name' => 'Central African Republic',
                'iso_alpha_2' => 'CF',
                'iso_alpha_3' => 'CAF',
                'iso_numeric' => '140',
                'international_phone' => '236',
            ],
            [
                'name' => 'Chad',
                'iso_alpha_2' => 'TD',
                'iso_alpha_3' => 'TCD',
                'iso_numeric' => '148',
                'international_phone' => '235',
            ],
            [
                'name' => 'Comoros',
                'iso_alpha_2' => 'KM',
                'iso_alpha_3' => 'COM',
                'iso_numeric' => '174',
                'international_phone' => '269',
            ],
            [
                'name' => 'Congo - Brazzaville',
                'iso_alpha_2' => 'CG',
                'iso_alpha_3' => 'COG',
                'iso_numeric' => '178',
                'international_phone' => '242',
            ],
            [
                'name' => 'Congo - Kinshasa',
                'iso_alpha_2' => 'CD',
                'iso_alpha_3' => 'COD',
                'iso_numeric' => '180',
                'international_phone' => '243',
            ],
            [
                'name' => 'Côte d’Ivoire',
                'iso_alpha_2' => 'CI',
                'iso_alpha_3' => 'CIV',
                'iso_numeric' => '384',
                'international_phone' => '225',
            ],
            [
                'name' => 'Djibouti',
                'iso_alpha_2' => 'DJ',
                'iso_alpha_3' => 'DJI',
                'iso_numeric' => '262',
                'international_phone' => '253',
            ],
            [
                'name' => 'Egypt',
                'iso_alpha_2' => 'EG',
                'iso_alpha_3' => 'EGY',
                'iso_numeric' => '818',
                'international_phone' => '20',
            ],
            [
                'name' => 'Equatorial Guinea',
                'iso_alpha_2' => 'GQ',
                'iso_alpha_3' => 'GNQ',
                'iso_numeric' => '226',
                'international_phone' => '240',
            ],
            [
                'name' => 'Eritrea',
                'iso_alpha_2' => 'ER',
                'iso_alpha_3' => 'ERI',
                'iso_numeric' => '232',
                'international_phone' => '291',
            ],
            [
                'name' => 'Ethiopia',
                'iso_alpha_2' => 'ET',
                'iso_alpha_3' => 'ETH',
                'iso_numeric' => '231',
                'international_phone' => '251',
            ],
            [
                'name' => 'Gabon',
                'iso_alpha_2' => 'GA',
                'iso_alpha_3' => 'GAB',
                'iso_numeric' => '266',
                'international_phone' => '241',
            ],
            [
                'name' => 'Gambia',
                'iso_alpha_2' => 'GM',
                'iso_alpha_3' => 'GMB',
                'iso_numeric' => '270',
                'international_phone' => '220',
            ],
            [
                'name' => 'Ghana',
                'iso_alpha_2' => 'GH',
                'iso_alpha_3' => 'GHA',
                'iso_numeric' => '288',
                'international_phone' => '233',
            ],
            [
                'name' => 'Guinea',
                'iso_alpha_2' => 'GN',
                'iso_alpha_3' => 'GIN',
                'iso_numeric' => '324',
                'international_phone' => '224',
            ],
            [
                'name' => 'Guinea-Bissau',
                'iso_alpha_2' => 'GW',
                'iso_alpha_3' => 'GNB',
                'iso_numeric' => '624',
                'international_phone' => '245',
            ],
            [
                'name' => 'Kenya',
                'iso_alpha_2' => 'KE',
                'iso_alpha_3' => 'KEN',
                'iso_numeric' => '404',
                'international_phone' => '254',
            ],
            [
                'name' => 'Lesotho',
                'iso_alpha_2' => 'LS',
                'iso_alpha_3' => 'LSO',
                'iso_numeric' => '426',
                'international_phone' => '266',
            ],
            [
                'name' => 'Liberia',
                'iso_alpha_2' => 'LR',
                'iso_alpha_3' => 'LBR',
                'iso_numeric' => '430',
                'international_phone' => '231',
            ],
            [
                'name' => 'Libya',
                'iso_alpha_2' => 'LY',
                'iso_alpha_3' => 'LBY',
                'iso_numeric' => '434',
                'international_phone' => '218',
            ],
            [
                'name' => 'Madagascar',
                'iso_alpha_2' => 'MG',
                'iso_alpha_3' => 'MDG',
                'iso_numeric' => '450',
                'international_phone' => '261',
            ],
            [
                'name' => 'Malawi',
                'iso_alpha_2' => 'MW',
                'iso_alpha_3' => 'MWI',
                'iso_numeric' => '454',
                'international_phone' => '265',
            ],
            [
                'name' => 'Mali',
                'iso_alpha_2' => 'ML',
                'iso_alpha_3' => 'MLI',
                'iso_numeric' => '466',
                'international_phone' => '223',
            ],
            [
                'name' => 'Mauritania',
                'iso_alpha_2' => 'MR',
                'iso_alpha_3' => 'MRT',
                'iso_numeric' => '478',
                'international_phone' => '222',
            ],
            [
                'name' => 'Mauritius',
                'iso_alpha_2' => 'MU',
                'iso_alpha_3' => 'MUS',
                'iso_numeric' => '480',
                'international_phone' => '230',
            ],
            [
                'name' => 'Mayotte',
                'iso_alpha_2' => 'YT',
                'iso_alpha_3' => 'MYT',
                'iso_numeric' => '175',
                'international_phone' => '262',
            ],
            [
                'name' => 'Morocco',
                'iso_alpha_2' => 'MA',
                'iso_alpha_3' => 'MAR',
                'iso_numeric' => '504',
                'international_phone' => '212',
            ],
            [
                'name' => 'Mozambique',
                'iso_alpha_2' => 'MZ',
                'iso_alpha_3' => 'MOZ',
                'iso_numeric' => '508',
                'international_phone' => '258',
            ],
            [
                'name' => 'Namibia',
                'iso_alpha_2' => 'NA',
                'iso_alpha_3' => 'NAM',
                'iso_numeric' => '516',
                'international_phone' => '264',
            ],
            [
                'name' => 'Niger',
                'iso_alpha_2' => 'NE',
                'iso_alpha_3' => 'NER',
                'iso_numeric' => '562',
                'international_phone' => '227',
            ],
            [
                'name' => 'Nigeria',
                'iso_alpha_2' => 'NG',
                'iso_alpha_3' => 'NGA',
                'iso_numeric' => '566',
                'international_phone' => '234',
            ],
            [
                'name' => 'Rwanda',
                'iso_alpha_2' => 'RW',
                'iso_alpha_3' => 'RWA',
                'iso_numeric' => '646',
                'international_phone' => '250',
            ],
            [
                'name' => 'Réunion',
                'iso_alpha_2' => 'RE',
                'iso_alpha_3' => 'REU',
                'iso_numeric' => '638',
                'international_phone' => '262',
            ],
            [
                'name' => 'Saint Helena',
                'iso_alpha_2' => 'SH',
                'iso_alpha_3' => 'SHN',
                'iso_numeric' => '654',
                'international_phone' => '290',
            ],
            [
                'name' => 'Senegal',
                'iso_alpha_2' => 'SN',
                'iso_alpha_3' => 'SEN',
                'iso_numeric' => '686',
                'international_phone' => '221',
            ],
            [
                'name' => 'Seychelles',
                'iso_alpha_2' => 'SC',
                'iso_alpha_3' => 'SYC',
                'iso_numeric' => '690',
                'international_phone' => '248',
            ],
            [
                'name' => 'Sierra Leone',
                'iso_alpha_2' => 'SL',
                'iso_alpha_3' => 'SLE',
                'iso_numeric' => '694',
                'international_phone' => '232',
            ],
            [
                'name' => 'Somalia',
                'iso_alpha_2' => 'SO',
                'iso_alpha_3' => 'SOM',
                'iso_numeric' => '706',
                'international_phone' => '252',
            ],
            [
                'name' => 'South Africa',
                'iso_alpha_2' => 'ZA',
                'iso_alpha_3' => 'ZAF',
                'iso_numeric' => '710',
                'international_phone' => '27',
            ],
            [
                'name' => 'Sudan',
                'iso_alpha_2' => 'SD',
                'iso_alpha_3' => 'SDN',
                'iso_numeric' => '736',
                'international_phone' => '249',
            ],
            [
                'name' => 'Swaziland',
                'iso_alpha_2' => 'SZ',
                'iso_alpha_3' => 'SWZ',
                'iso_numeric' => '748',
                'international_phone' => '268',
            ],
            [
                'name' => 'São Tomé and Príncipe',
                'iso_alpha_2' => 'ST',
                'iso_alpha_3' => 'STP',
                'iso_numeric' => '678',
                'international_phone' => '239',
            ],
            [
                'name' => 'Tanzania',
                'iso_alpha_2' => 'TZ',
                'iso_alpha_3' => 'TZA',
                'iso_numeric' => '834',
                'international_phone' => '255',
            ],
            [
                'name' => 'Togo',
                'iso_alpha_2' => 'TG',
                'iso_alpha_3' => 'TGO',
                'iso_numeric' => '768',
                'international_phone' => '228',
            ],
            [
                'name' => 'Tunisia',
                'iso_alpha_2' => 'TN',
                'iso_alpha_3' => 'TUN',
                'iso_numeric' => '788',
                'international_phone' => '216',
            ],
            [
                'name' => 'Uganda',
                'iso_alpha_2' => 'UG',
                'iso_alpha_3' => 'UGA',
                'iso_numeric' => '800',
                'international_phone' => '256',
            ],
            [
                'name' => 'Western Sahara',
                'iso_alpha_2' => 'EH',
                'iso_alpha_3' => 'ESH',
                'iso_numeric' => '732',
                'international_phone' => '212',
            ],
            [
                'name' => 'Zambia',
                'iso_alpha_2' => 'ZM',
                'iso_alpha_3' => 'ZMB',
                'iso_numeric' => '894',
                'international_phone' => '260',
            ],
            [
                'name' => 'Zimbabwe',
                'iso_alpha_2' => 'ZW',
                'iso_alpha_3' => 'ZWE',
                'iso_numeric' => '716',
                'international_phone' => '263',
            ],
            [
                'name' => 'Anguilla',
                'iso_alpha_2' => 'AI',
                'iso_alpha_3' => 'AIA',
                'iso_numeric' => '660',
                'international_phone' => '1-264',
            ],
            [
                'name' => 'Antigua and Barbuda',
                'iso_alpha_2' => 'AG',
                'iso_alpha_3' => 'ATG',
                'iso_numeric' => '28',
                'international_phone' => '1-268',
            ],
            [
                'name' => 'Argentina',
                'iso_alpha_2' => 'AR',
                'iso_alpha_3' => 'ARG',
                'iso_numeric' => '32',
                'international_phone' => '54',
            ],
            [
                'name' => 'Aruba',
                'iso_alpha_2' => 'AW',
                'iso_alpha_3' => 'ABW',
                'iso_numeric' => '533',
                'international_phone' => '297',
            ],
            [
                'name' => 'Bahamas',
                'iso_alpha_2' => 'BS',
                'iso_alpha_3' => 'BHS',
                'iso_numeric' => '44',
                'international_phone' => '1-242',
            ],
            [
                'name' => 'Barbados',
                'iso_alpha_2' => 'BB',
                'iso_alpha_3' => 'BRB',
                'iso_numeric' => '52',
                'international_phone' => '1-246',
            ],
            [
                'name' => 'Belize',
                'iso_alpha_2' => 'BZ',
                'iso_alpha_3' => 'BLZ',
                'iso_numeric' => '84',
                'international_phone' => '501',
            ],
            [
                'name' => 'Bermuda',
                'iso_alpha_2' => 'BM',
                'iso_alpha_3' => 'BMU',
                'iso_numeric' => '60',
                'international_phone' => '1-441',
            ],
            [
                'name' => 'Bolivia',
                'iso_alpha_2' => 'BO',
                'iso_alpha_3' => 'BOL',
                'iso_numeric' => '68',
                'international_phone' => '591',
            ],
            [
                'name' => 'Brazil',
                'iso_alpha_2' => 'BR',
                'iso_alpha_3' => 'BRA',
                'iso_numeric' => '76',
                'international_phone' => '55',
            ],
            [
                'name' => 'British Virgin Islands',
                'iso_alpha_2' => 'VG',
                'iso_alpha_3' => 'VGB',
                'iso_numeric' => '92',
                'international_phone' => '1-284',
            ],
            [
                'name' => 'Canada',
                'iso_alpha_2' => 'CA',
                'iso_alpha_3' => 'CAN',
                'iso_numeric' => '124',
                'international_phone' => '1',
            ],
            [
                'name' => 'Cayman Islands',
                'iso_alpha_2' => 'KY',
                'iso_alpha_3' => 'CYM',
                'iso_numeric' => '163',
                'international_phone' => '1-345',
            ],
            [
                'name' => 'Chile',
                'iso_alpha_2' => 'CL',
                'iso_alpha_3' => 'CHL',
                'iso_numeric' => '152',
                'international_phone' => '56',
            ],
            [
                'name' => 'Colombia',
                'iso_alpha_2' => 'CO',
                'iso_alpha_3' => 'COL',
                'iso_numeric' => '170',
                'international_phone' => '57',
            ],
            [
                'name' => 'Costa Rica',
                'iso_alpha_2' => 'CR',
                'iso_alpha_3' => 'CRI',
                'iso_numeric' => '188',
                'international_phone' => '506',
            ],
            [
                'name' => 'Cuba',
                'iso_alpha_2' => 'CU',
                'iso_alpha_3' => 'CUB',
                'iso_numeric' => '192',
                'international_phone' => '53',
            ],
            [
                'name' => 'Dominica',
                'iso_alpha_2' => 'DM',
                'iso_alpha_3' => 'DMA',
                'iso_numeric' => '212',
                'international_phone' => '1-767',
            ],
            [
                'name' => 'Dominican Republic',
                'iso_alpha_2' => 'DO',
                'iso_alpha_3' => 'DOM',
                'iso_numeric' => '214',
                'international_phone' => '1-809,1-829,1-849',
            ],
            [
                'name' => 'Ecuador',
                'iso_alpha_2' => 'EC',
                'iso_alpha_3' => 'ECU',
                'iso_numeric' => '218',
                'international_phone' => '593',
            ],
            [
                'name' => 'El Salvador',
                'iso_alpha_2' => 'SV',
                'iso_alpha_3' => 'SLV',
                'iso_numeric' => '222',
                'international_phone' => '503',
            ],
            [
                'name' => 'Falkland Islands',
                'iso_alpha_2' => 'FK',
                'iso_alpha_3' => 'FLK',
                'iso_numeric' => '238',
                'international_phone' => '500',
            ],
            [
                'name' => 'French Guiana',
                'iso_alpha_2' => 'GF',
                'iso_alpha_3' => 'GUF',
                'iso_numeric' => '254',
                'international_phone' => '594',
            ],
            [
                'name' => 'Greenland',
                'iso_alpha_2' => 'GL',
                'iso_alpha_3' => 'GRL',
                'iso_numeric' => '304',
                'international_phone' => '299',
            ],
            [
                'name' => 'Grenada',
                'iso_alpha_2' => 'GD',
                'iso_alpha_3' => 'GRD',
                'iso_numeric' => '308',
                'international_phone' => '1-473',
            ],
            [
                'name' => 'Guadeloupe',
                'iso_alpha_2' => 'GP',
                'iso_alpha_3' => 'GLP',
                'iso_numeric' => '312',
                'international_phone' => '590',
            ],
            [
                'name' => 'Guatemala',
                'iso_alpha_2' => 'GT',
                'iso_alpha_3' => 'GTM',
                'iso_numeric' => '320',
                'international_phone' => '502',
            ],
            [
                'name' => 'Guyana',
                'iso_alpha_2' => 'GY',
                'iso_alpha_3' => 'GUY',
                'iso_numeric' => '328',
                'international_phone' => '592',
            ],
            [
                'name' => 'Haiti',
                'iso_alpha_2' => 'HT',
                'iso_alpha_3' => 'HTI',
                'iso_numeric' => '332',
                'international_phone' => '509',
            ],
            [
                'name' => 'Honduras',
                'iso_alpha_2' => 'HN',
                'iso_alpha_3' => 'HND',
                'iso_numeric' => '340',
                'international_phone' => '504',
            ],
            [
                'name' => 'Jamaica',
                'iso_alpha_2' => 'JM',
                'iso_alpha_3' => 'JAM',
                'iso_numeric' => '388',
                'international_phone' => '1-876',
            ],
            [
                'name' => 'Martinique',
                'iso_alpha_2' => 'MQ',
                'iso_alpha_3' => 'MTQ',
                'iso_numeric' => '474',
                'international_phone' => '596',
            ],
            [
                'name' => 'Mexico',
                'iso_alpha_2' => 'MX',
                'iso_alpha_3' => 'MEX',
                'iso_numeric' => '484',
                'international_phone' => '52',
            ],
            [
                'name' => 'Montserrat',
                'iso_alpha_2' => 'MS',
                'iso_alpha_3' => 'MSR',
                'iso_numeric' => '500',
                'international_phone' => '1-664',
            ],
            [
                'name' => 'Netherlands Antilles',
                'iso_alpha_2' => 'AN',
                'iso_alpha_3' => 'ANT',
                'iso_numeric' => '530',
                'international_phone' => '599',
            ],
            [
                'name' => 'Nicaragua',
                'iso_alpha_2' => 'NI',
                'iso_alpha_3' => 'NIC',
                'iso_numeric' => '558',
                'international_phone' => '505',
            ],
            [
                'name' => 'Panama',
                'iso_alpha_2' => 'PA',
                'iso_alpha_3' => 'PAN',
                'iso_numeric' => '591',
                'international_phone' => '507',
            ],
            [
                'name' => 'Paraguay',
                'iso_alpha_2' => 'PY',
                'iso_alpha_3' => 'PRY',
                'iso_numeric' => '600',
                'international_phone' => '595',
            ],
            [
                'name' => 'Peru',
                'iso_alpha_2' => 'PE',
                'iso_alpha_3' => 'PER',
                'iso_numeric' => '604',
                'international_phone' => '51',
            ],
            [
                'name' => 'Puerto Rico',
                'iso_alpha_2' => 'PR',
                'iso_alpha_3' => 'PRI',
                'iso_numeric' => '630',
                'international_phone' => '1',
            ],
            [
                'name' => 'Saint Barthélemy',
                'iso_alpha_2' => 'BL',
                'iso_alpha_3' => 'BLM',
                'iso_numeric' => '652',
                'international_phone' => '590',
            ],
            [
                'name' => 'Saint Kitts and Nevis',
                'iso_alpha_2' => 'KN',
                'iso_alpha_3' => 'KNA',
                'iso_numeric' => '659',
                'international_phone' => '1-869',
            ],
            [
                'name' => 'Saint Lucia',
                'iso_alpha_2' => 'LC',
                'iso_alpha_3' => 'LCA',
                'iso_numeric' => '662',
                'international_phone' => '1-758',
            ],
            [
                'name' => 'Saint Martin',
                'iso_alpha_2' => 'MF',
                'iso_alpha_3' => 'MAF',
                'iso_numeric' => '663',
                'international_phone' => '590',
            ],
            [
                'name' => 'Saint Pierre and Miquelon',
                'iso_alpha_2' => 'PM',
                'iso_alpha_3' => 'SPM',
                'iso_numeric' => '666',
                'international_phone' => '508',
            ],
            [
                'name' => 'Saint Vincent and Grenadines',
                'iso_alpha_2' => 'VC',
                'iso_alpha_3' => 'VCT',
                'iso_numeric' => '670',
                'international_phone' => '1-784',
            ],
            [
                'name' => 'Suriname',
                'iso_alpha_2' => 'SR',
                'iso_alpha_3' => 'SUR',
                'iso_numeric' => '740',
                'international_phone' => '597',
            ],
            [
                'name' => 'Trinidad and Tobago',
                'iso_alpha_2' => 'TT',
                'iso_alpha_3' => 'TTO',
                'iso_numeric' => '780',
                'international_phone' => '1-868',
            ],
            [
                'name' => 'Turks and Caicos Islands',
                'iso_alpha_2' => 'TC',
                'iso_alpha_3' => 'TCA',
                'iso_numeric' => '796',
                'international_phone' => '1-649',
            ],
            [
                'name' => 'Virgin Islands, US',
                'iso_alpha_2' => 'VI',
                'iso_alpha_3' => 'VIR',
                'iso_numeric' => '850',
                'international_phone' => '1-340',
            ],
            [
                'name' => 'United States of America',
                'iso_alpha_2' => 'US',
                'iso_alpha_3' => 'USA',
                'iso_numeric' => '840',
                'international_phone' => '1',
            ],
            [
                'name' => 'Uruguay',
                'iso_alpha_2' => 'UY',
                'iso_alpha_3' => 'URY',
                'iso_numeric' => '858',
                'international_phone' => '598',
            ],
            [
                'name' => 'Venezuela',
                'iso_alpha_2' => 'VE',
                'iso_alpha_3' => 'VEN',
                'iso_numeric' => '862',
                'international_phone' => '58',
            ],
            [
                'name' => 'Afghanistan',
                'iso_alpha_2' => 'AF',
                'iso_alpha_3' => 'AFG',
                'iso_numeric' => '4',
                'international_phone' => '93',
            ],
            [
                'name' => 'Armenia',
                'iso_alpha_2' => 'AM',
                'iso_alpha_3' => 'ARM',
                'iso_numeric' => '51',
                'international_phone' => '374',
            ],
            [
                'name' => 'Azerbaijan',
                'iso_alpha_2' => 'AZ',
                'iso_alpha_3' => 'AZE',
                'iso_numeric' => '31',
                'international_phone' => '994',
            ],
            [
                'name' => 'Bahrain',
                'iso_alpha_2' => 'BH',
                'iso_alpha_3' => 'BHR',
                'iso_numeric' => '48',
                'international_phone' => '973',
            ],
            [
                'name' => 'Bangladesh',
                'iso_alpha_2' => 'BD',
                'iso_alpha_3' => 'BGD',
                'iso_numeric' => '50',
                'international_phone' => '880',
            ],
            [
                'name' => 'Bhutan',
                'iso_alpha_2' => 'BT',
                'iso_alpha_3' => 'BTN',
                'iso_numeric' => '64',
                'international_phone' => '975',
            ],
            [
                'name' => 'Brunei Darussalam',
                'iso_alpha_2' => 'BN',
                'iso_alpha_3' => 'BRN',
                'iso_numeric' => '96',
                'international_phone' => '673',
            ],
            [
                'name' => 'Cambodia',
                'iso_alpha_2' => 'KH',
                'iso_alpha_3' => 'KHM',
                'iso_numeric' => '116',
                'international_phone' => '855',
            ],
            [
                'name' => 'China',
                'iso_alpha_2' => 'CN',
                'iso_alpha_3' => 'CHN',
                'iso_numeric' => '156',
                'international_phone' => '86',
            ],
            [
                'name' => 'Georgia',
                'iso_alpha_2' => 'GE',
                'iso_alpha_3' => 'GEO',
                'iso_numeric' => '268',
                'international_phone' => '995',
            ],
            [
                'name' => 'Hong Kong SAR China',
                'iso_alpha_2' => 'HK',
                'iso_alpha_3' => 'HKG',
                'iso_numeric' => '344',
                'international_phone' => '852',
            ],
            [
                'name' => 'India',
                'iso_alpha_2' => 'IN',
                'iso_alpha_3' => 'IND',
                'iso_numeric' => '356',
                'international_phone' => '91',
            ],
            [
                'name' => 'Indonesia',
                'iso_alpha_2' => 'ID',
                'iso_alpha_3' => 'IDN',
                'iso_numeric' => '360',
                'international_phone' => '62',
            ],
            [
                'name' => 'Iran',
                'iso_alpha_2' => 'IR',
                'iso_alpha_3' => 'IRN',
                'iso_numeric' => '364',
                'international_phone' => '98',
            ],
            [
                'name' => 'Iraq',
                'iso_alpha_2' => 'IQ',
                'iso_alpha_3' => 'IRQ',
                'iso_numeric' => '368',
                'international_phone' => '964',
            ],
            [
                'name' => 'Israel',
                'iso_alpha_2' => 'IL',
                'iso_alpha_3' => 'ISR',
                'iso_numeric' => '376',
                'international_phone' => '972',
            ],
            [
                'name' => 'Japan',
                'iso_alpha_2' => 'JP',
                'iso_alpha_3' => 'JPN',
                'iso_numeric' => '392',
                'international_phone' => '81',
            ],
            [
                'name' => 'Jordan',
                'iso_alpha_2' => 'JO',
                'iso_alpha_3' => 'JOR',
                'iso_numeric' => '400',
                'international_phone' => '962',
            ],
            [
                'name' => 'Kazakhstan',
                'iso_alpha_2' => 'KZ',
                'iso_alpha_3' => 'KAZ',
                'iso_numeric' => '398',
                'international_phone' => '7',
            ],
            [
                'name' => 'Kuwait',
                'iso_alpha_2' => 'KW',
                'iso_alpha_3' => 'KWT',
                'iso_numeric' => '414',
                'international_phone' => '965',
            ],
            [
                'name' => 'Kyrgyzstan',
                'iso_alpha_2' => 'KG',
                'iso_alpha_3' => 'KGZ',
                'iso_numeric' => '417',
                'international_phone' => '996',
            ],
            [
                'name' => 'Lao PDR',
                'iso_alpha_2' => 'LA',
                'iso_alpha_3' => 'LAO',
                'iso_numeric' => '418',
                'international_phone' => '856',
            ],
            [
                'name' => 'Lebanon',
                'iso_alpha_2' => 'LB',
                'iso_alpha_3' => 'LBN',
                'iso_numeric' => '422',
                'international_phone' => '961',
            ],
            [
                'name' => 'Macau SAR China',
                'iso_alpha_2' => 'MO',
                'iso_alpha_3' => 'MAC',
                'iso_numeric' => '446',
                'international_phone' => '853',
            ],
            [
                'name' => 'Malaysia',
                'iso_alpha_2' => 'MY',
                'iso_alpha_3' => 'MYS',
                'iso_numeric' => '458',
                'international_phone' => '60',
            ],
            [
                'name' => 'Maldives',
                'iso_alpha_2' => 'MV',
                'iso_alpha_3' => 'MDV',
                'iso_numeric' => '462',
                'international_phone' => '960',
            ],
            [
                'name' => 'Mongolia',
                'iso_alpha_2' => 'MN',
                'iso_alpha_3' => 'MNG',
                'iso_numeric' => '496',
                'international_phone' => '976',
            ],
            [
                'name' => 'Myanmar',
                'iso_alpha_2' => 'MM',
                'iso_alpha_3' => 'MMR',
                'iso_numeric' => '104',
                'international_phone' => '95',
            ],
            [
                'name' => 'Nepal',
                'iso_alpha_2' => 'NP',
                'iso_alpha_3' => 'NPL',
                'iso_numeric' => '524',
                'international_phone' => '977',
            ],
            [
                'name' => 'Neutral Zone',
                'iso_alpha_2' => 'NT',
                'iso_alpha_3' => 'NTZ',
                'iso_numeric' => '1058',
                'international_phone' => null,
            ],
            [
                'name' => 'North Korea',
                'iso_alpha_2' => 'KP',
                'iso_alpha_3' => 'PRK',
                'iso_numeric' => '408',
                'international_phone' => '850',
            ],
            [
                'name' => 'Oman',
                'iso_alpha_2' => 'OM',
                'iso_alpha_3' => 'OMN',
                'iso_numeric' => '512',
                'international_phone' => '968',
            ],
            [
                'name' => 'Pakistan',
                'iso_alpha_2' => 'PK',
                'iso_alpha_3' => 'PAK',
                'iso_numeric' => '586',
                'international_phone' => '92',
            ],
            [
                'name' => 'Palestinian Territory',
                'iso_alpha_2' => 'PS',
                'iso_alpha_3' => 'PSE',
                'iso_numeric' => '275',
                'international_phone' => '970',
            ],
            [
                'name' => 'People\'s Democratic Republic of Yemen',
                'iso_alpha_2' => 'YD',
                'iso_alpha_3' => 'YDD',
                'iso_numeric' => null,
                'international_phone' => '967',
            ],
            [
                'name' => 'Philippines',
                'iso_alpha_2' => 'ph',
                'iso_alpha_3' => 'PHL',
                'iso_numeric' => '608',
                'international_phone' => '63',
            ],
            [
                'name' => 'Qatar',
                'iso_alpha_2' => 'QA',
                'iso_alpha_3' => 'QAT',
                'iso_numeric' => '634',
                'international_phone' => '974',
            ],
            [
                'name' => 'Saudi Arabia',
                'iso_alpha_2' => 'SA',
                'iso_alpha_3' => 'SAU',
                'iso_numeric' => '682',
                'international_phone' => '966',
            ],
            [
                'name' => 'Singapore',
                'iso_alpha_2' => 'SG',
                'iso_alpha_3' => 'SGP',
                'iso_numeric' => '702',
                'international_phone' => '65',
            ],
            [
                'name' => 'South Korea',
                'iso_alpha_2' => 'KR',
                'iso_alpha_3' => 'KOR',
                'iso_numeric' => '410',
                'international_phone' => '82',
            ],
            [
                'name' => 'Sri Lanka',
                'iso_alpha_2' => 'LK',
                'iso_alpha_3' => 'LKA',
                'iso_numeric' => '144',
                'international_phone' => '94',
            ],
            [
                'name' => 'Syria',
                'iso_alpha_2' => 'SY',
                'iso_alpha_3' => 'SYR',
                'iso_numeric' => '760',
                'international_phone' => '963',
            ],
            [
                'name' => 'Taiwan',
                'iso_alpha_2' => 'TW',
                'iso_alpha_3' => 'TWN',
                'iso_numeric' => '158',
                'international_phone' => '886',
            ],
            [
                'name' => 'Tajikistan',
                'iso_alpha_2' => 'TJ',
                'iso_alpha_3' => 'TJK',
                'iso_numeric' => '762',
                'international_phone' => '992',
            ],
            [
                'name' => 'Thailand',
                'iso_alpha_2' => 'TH',
                'iso_alpha_3' => 'THA',
                'iso_numeric' => '764',
                'international_phone' => '66',
            ],
            [
                'name' => 'Timor-Leste',
                'iso_alpha_2' => 'TL',
                'iso_alpha_3' => 'TLS',
                'iso_numeric' => '626',
                'international_phone' => '670',
            ],
            [
                'name' => 'Turkey',
                'iso_alpha_2' => 'TR',
                'iso_alpha_3' => 'TUR',
                'iso_numeric' => '792',
                'international_phone' => '90',
            ],
            [
                'name' => 'Turkmenistan',
                'iso_alpha_2' => 'TM',
                'iso_alpha_3' => 'TKM',
                'iso_numeric' => '795',
                'international_phone' => '993',
            ],
            [
                'name' => 'United Arab Emirates',
                'iso_alpha_2' => 'AE',
                'iso_alpha_3' => 'ARE',
                'iso_numeric' => '784',
                'international_phone' => '971',
            ],
            [
                'name' => 'Uzbekistan',
                'iso_alpha_2' => 'UZ',
                'iso_alpha_3' => 'UZB',
                'iso_numeric' => '860',
                'international_phone' => '998',
            ],
            [
                'name' => 'Vietnam',
                'iso_alpha_2' => 'VN',
                'iso_alpha_3' => 'VNM',
                'iso_numeric' => '704',
                'international_phone' => '84',
            ],
            [
                'name' => 'Yemen',
                'iso_alpha_2' => 'YE',
                'iso_alpha_3' => 'YEM',
                'iso_numeric' => '887',
                'international_phone' => '967',
            ],
            [
                'name' => 'American Samoa',
                'iso_alpha_2' => 'AS',
                'iso_alpha_3' => 'ASM',
                'iso_numeric' => '16',
                'international_phone' => '1-684',
            ],
            [
                'name' => 'Antarctica',
                'iso_alpha_2' => 'AQ',
                'iso_alpha_3' => 'ATA',
                'iso_numeric' => '10',
                'international_phone' => '672',
            ],
            [
                'name' => 'Bouvet Island',
                'iso_alpha_2' => 'BV',
                'iso_alpha_3' => 'BVT',
                'iso_numeric' => '74',
                'international_phone' => '47',
            ],
            [
                'name' => 'British Indian Ocean Territory',
                'iso_alpha_2' => 'IO',
                'iso_alpha_3' => 'IOT',
                'iso_numeric' => '86',
                'international_phone' => '246',
            ],
            [
                'name' => 'Christmas Island',
                'iso_alpha_2' => 'CX',
                'iso_alpha_3' => 'CXR',
                'iso_numeric' => '162',
                'international_phone' => '61',
            ],
            [
                'name' => 'Cocos [Keeling] Islands',
                'iso_alpha_2' => 'CC',
                'iso_alpha_3' => 'CCK',
                'iso_numeric' => '166',
                'international_phone' => '61',
            ],
            [
                'name' => 'Cook Islands',
                'iso_alpha_2' => 'CK',
                'iso_alpha_3' => 'COK',
                'iso_numeric' => '184',
                'international_phone' => '682',
            ],
            [
                'name' => 'Fiji',
                'iso_alpha_2' => 'FJ',
                'iso_alpha_3' => 'FJI',
                'iso_numeric' => '242',
                'international_phone' => '679',
            ],
            [
                'name' => 'French Polynesia',
                'iso_alpha_2' => 'PF',
                'iso_alpha_3' => 'PYF',
                'iso_numeric' => '258',
                'international_phone' => '689',
            ],
            [
                'name' => 'French Southern Territories',
                'iso_alpha_2' => 'TF',
                'iso_alpha_3' => 'ATF',
                'iso_numeric' => '260',
                'international_phone' => '262',
            ],
            [
                'name' => 'Guam',
                'iso_alpha_2' => 'GU',
                'iso_alpha_3' => 'GUM',
                'iso_numeric' => '316',
                'international_phone' => '1-671',
            ],
            [
                'name' => 'Heard Island and McDonald Islands',
                'iso_alpha_2' => 'HM',
                'iso_alpha_3' => 'HMD',
                'iso_numeric' => '672',
                'international_phone' => '672',
            ],
            [
                'name' => 'Kiribati',
                'iso_alpha_2' => 'KI',
                'iso_alpha_3' => 'KIR',
                'iso_numeric' => '296',
                'international_phone' => '686',
            ],
            [
                'name' => 'Marshall Islands',
                'iso_alpha_2' => 'MH',
                'iso_alpha_3' => 'MHL',
                'iso_numeric' => '584',
                'international_phone' => '692',
            ],
            [
                'name' => 'Micronesia',
                'iso_alpha_2' => 'FM',
                'iso_alpha_3' => 'FSM',
                'iso_numeric' => '583',
                'international_phone' => '691',
            ],
            [
                'name' => 'Nauru',
                'iso_alpha_2' => 'NR',
                'iso_alpha_3' => 'NRU',
                'iso_numeric' => '520',
                'international_phone' => '674',
            ],
            [
                'name' => 'New Caledonia',
                'iso_alpha_2' => 'NC',
                'iso_alpha_3' => 'NCL',
                'iso_numeric' => '540',
                'international_phone' => '687',
            ],
            [
                'name' => 'New Zealand',
                'iso_alpha_2' => 'NZ',
                'iso_alpha_3' => 'NZL',
                'iso_numeric' => '544',
                'international_phone' => '64',
            ],
            [
                'name' => 'Niue',
                'iso_alpha_2' => 'NU',
                'iso_alpha_3' => 'NIU',
                'iso_numeric' => '570',
                'international_phone' => '683',
            ],
            [
                'name' => 'Norfolk Island',
                'iso_alpha_2' => 'NF',
                'iso_alpha_3' => 'NFK',
                'iso_numeric' => '574',
                'international_phone' => '672',
            ],
            [
                'name' => 'Northern Mariana Islands',
                'iso_alpha_2' => 'MP',
                'iso_alpha_3' => 'MNP',
                'iso_numeric' => '580',
                'international_phone' => '1-670',
            ],
            [
                'name' => 'Palau',
                'iso_alpha_2' => 'PW',
                'iso_alpha_3' => 'PLW',
                'iso_numeric' => '585',
                'international_phone' => '680',
            ],
            [
                'name' => 'Papua New Guinea',
                'iso_alpha_2' => 'PG',
                'iso_alpha_3' => 'PNG',
                'iso_numeric' => '598',
                'international_phone' => '680',
            ],
            [
                'name' => 'Pitcairn Islands',
                'iso_alpha_2' => 'PN',
                'iso_alpha_3' => 'PCN',
                'iso_numeric' => '612',
                'international_phone' => '64',
            ],
            [
                'name' => 'Samoa',
                'iso_alpha_2' => 'WS',
                'iso_alpha_3' => 'WSM',
                'iso_numeric' => '882',
                'international_phone' => '685',
            ],
            [
                'name' => 'Solomon Islands',
                'iso_alpha_2' => 'SB',
                'iso_alpha_3' => 'SLB',
                'iso_numeric' => '90',
                'international_phone' => '677',
            ],
            [
                'name' => 'South Georgia and the South Sandwich Islands',
                'iso_alpha_2' => 'GS',
                'iso_alpha_3' => 'SGS',
                'iso_numeric' => '239',
                'international_phone' => '500',
            ],
            [
                'name' => 'Tokelau',
                'iso_alpha_2' => 'TK',
                'iso_alpha_3' => 'TKL',
                'iso_numeric' => '772',
                'international_phone' => '690',
            ],
            [
                'name' => 'Tonga',
                'iso_alpha_2' => 'TO',
                'iso_alpha_3' => 'TON',
                'iso_numeric' => '776',
                'international_phone' => '676',
            ],
            [
                'name' => 'Tuvalu',
                'iso_alpha_2' => 'TV',
                'iso_alpha_3' => 'TUV',
                'iso_numeric' => '798',
                'international_phone' => '688',
            ],
            [
                'name' => 'U.S. Minor Outlying Islands',
                'iso_alpha_2' => 'UM',
                'iso_alpha_3' => 'UMI',
                'iso_numeric' => '581',
                'international_phone' => '1',
            ],
            [
                'name' => 'Vanuatu',
                'iso_alpha_2' => 'VU',
                'iso_alpha_3' => 'VUT',
                'iso_numeric' => '548',
                'international_phone' => '678',
            ],
            [
                'name' => 'Wallis and Futuna Islands',
                'iso_alpha_2' => 'WF',
                'iso_alpha_3' => 'WLF',
                'iso_numeric' => '876',
                'international_phone' => '681',
            ],
            [
                'name' => 'Australia',
                'iso_alpha_2' => 'AU',
                'iso_alpha_3' => 'AUS',
                'iso_numeric' => '36',
                'international_phone' => '61',
            ],
        ];

        foreach ($countries as $country) {
            LocationCountry::create($country);
        }

        LocationCountry::where('name', 'Spain')->update([
            'visible' => TRUE
        ]);
    }
}
